#!/bin/bash
cd /home/ubuntu/

# use systemd to start and monitor dotnet application
systemctl enable kestrel-lexwebchatbotapp.service
systemctl start kestrel-lexwebchatbotapp.service

# start apache
systemctl restart apache2.service
